/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      // Paleta via CSS custom properties — dark/light controlados por :root e .light
      colors: {
        bg:             'rgb(var(--c-bg) / <alpha-value>)',
        elevated:       'rgb(var(--c-elevated) / <alpha-value>)',
        surface:        'rgb(var(--c-surface) / <alpha-value>)',
        card:           'rgb(var(--c-card) / <alpha-value>)',
        'card-high':    'rgb(var(--c-card-high) / <alpha-value>)',
        'card-highest': 'rgb(var(--c-card-highest) / <alpha-value>)',

        primary:        'rgb(var(--c-primary) / <alpha-value>)',
        'primary-light':'rgb(var(--c-primary-light) / <alpha-value>)',
        'primary-dark': 'rgb(var(--c-primary-dark) / <alpha-value>)',
        accent:         'rgb(var(--c-primary) / <alpha-value>)',
        accent2:        'rgb(var(--c-cyan) / <alpha-value>)',
        cyan:           'rgb(var(--c-cyan) / <alpha-value>)',

        text:           'rgb(var(--c-text) / <alpha-value>)',
        secondary:      'rgb(var(--c-secondary) / <alpha-value>)',
        muted:          'rgb(var(--c-muted) / <alpha-value>)',
        disabled:       'rgb(var(--c-disabled) / <alpha-value>)',

        green:          'rgb(var(--c-green) / <alpha-value>)',
        yellow:         'rgb(var(--c-yellow) / <alpha-value>)',
        red:            'rgb(var(--c-red) / <alpha-value>)',
        orange:         'rgb(var(--c-orange) / <alpha-value>)',
        purple:         'rgb(var(--c-purple) / <alpha-value>)',
        pink:           'rgb(var(--c-pink) / <alpha-value>)',
        teal:           'rgb(var(--c-teal) / <alpha-value>)',
        // Token semântico de borda — substitui border-white/[0.07]
        border:         'rgb(var(--c-border) / <alpha-value>)',
      },

      fontFamily: {
        sans:     ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        headline: ['"Space Grotesk"', '"Inter"', 'system-ui', 'sans-serif'],
        mono:     ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },

      borderRadius: {
        xs:      '3px',
        sm:      '6px',
        DEFAULT: '10px',
        md:      '12px',
        lg:      '16px',
        xl:      '20px',
        pill:    '9999px',
      },

      boxShadow: {
        xs:         '0 1px 2px rgba(0,0,0,.40)',
        sm:         '0 1px 3px rgba(0,0,0,.40), 0 1px 2px rgba(0,0,0,.30)',
        md:         '0 4px 12px rgba(0,0,0,.45), 0 2px 4px rgba(0,0,0,.30)',
        lg:         '0 8px 24px rgba(0,0,0,.50), 0 4px 8px rgba(0,0,0,.35)',
        xl:         '0 16px 40px rgba(0,0,0,.55), 0 8px 16px rgba(0,0,0,.40)',
        '2xl':      '0 24px 60px rgba(0,0,0,.65), 0 12px 24px rgba(0,0,0,.50)',
        accent:     '0 4px 16px rgba(59,130,246,.18), 0 2px 6px rgba(59,130,246,.10)',
        'accent-lg':'0 8px 28px rgba(59,130,246,.22), 0 4px 10px rgba(59,130,246,.14)',
      },

      zIndex: {
        base:     '1',
        sticky:   '95',
        dropdown: '100',
        sidebar:  '200',
        header:   '300',
        drawer:   '600',
        modal:    '700',
        overlay:  '800',
        toast:    '9000',
        top:      '9999',
      },

      animation: {
        aurora:           'aurora 8s ease infinite',
        'fade-in':        'fadeIn .22s cubic-bezier(.4,0,.2,1)',
        'slide-up':       'slideUp .22s cubic-bezier(.4,0,.2,1)',
        'slide-down':     'slideDown .22s cubic-bezier(.4,0,.2,1)',
        'scale-in':       'scaleIn .22s cubic-bezier(.34,1.56,.64,1)',
        'page-enter':     'pageEnter .40s cubic-bezier(.4,0,.2,1) both',
        'card-enter':     'cardEnter .36s cubic-bezier(.34,1.56,.64,1) both',
        'float-up':       'floatUp .44s cubic-bezier(.4,0,.2,1) both',
        'glow-pulse':     'glowPulse 2.6s ease-in-out infinite',
        'shimmer':        'shimmer 1.6s linear infinite',
        'breathe':        'breathe 3.2s ease-in-out infinite',
        'slide-right':    'slideRight .32s cubic-bezier(.34,1.56,.64,1) both',
        'pop-in':         'popIn .24s cubic-bezier(.34,1.56,.64,1) both',
        'gradient-flow':  'gradientFlow 5s ease infinite',
        'glow-border':    'glowBorderPulse 2.8s ease-in-out infinite',
        'slide-left':     'slideInLeft .30s cubic-bezier(.34,1.56,.64,1) both',
        'count-up':       'countUp .42s cubic-bezier(.34,1.56,.64,1) both',
        'morph':          'morphBlob 9s ease-in-out infinite',
      },
      keyframes: {
        aurora: {
          '0%,100%': { backgroundPosition: '0% 50%' },
          '50%':     { backgroundPosition: '100% 50%' },
        },
        fadeIn:          { from: { opacity: '0' },                                                                      to: { opacity: '1' } },
        slideUp:         { from: { opacity: '0', transform: 'translateY(8px)' },                                        to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:       { from: { opacity: '0', transform: 'translateY(-8px)' },                                       to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:         { from: { opacity: '0', transform: 'scale(.92)' },                                             to: { opacity: '1', transform: 'scale(1)' } },
        pageEnter:       { from: { opacity: '0', transform: 'translateY(16px)' },                                       to: { opacity: '1', transform: 'translateY(0)' } },
        cardEnter:       { from: { opacity: '0', transform: 'scale(.93) translateY(12px)' },                            to: { opacity: '1', transform: 'scale(1)   translateY(0)' } },
        floatUp:         { from: { opacity: '0', transform: 'translateY(24px)' },                                       to: { opacity: '1', transform: 'translateY(0)' } },
        slideRight:      { from: { opacity: '0', transform: 'translateX(-14px)' },                                      to: { opacity: '1', transform: 'translateX(0)' } },
        popIn:           { from: { opacity: '0', transform: 'scale(.80)' },                                             to: { opacity: '1', transform: 'scale(1)' } },
        glowPulse:       { '0%,100%': { boxShadow: '0 0 0 0 rgba(14,165,233,0)' },     '50%': { boxShadow: '0 0 0 12px rgba(14,165,233,.12)' } },
        shimmer:         { from: { backgroundPosition: '-200% 0' },                                                     to:   { backgroundPosition: '200% 0' } },
        breathe:         { '0%,100%': { transform: 'scale(1)',    opacity: '0.7' },     '50%': { transform: 'scale(1.04)', opacity: '1' } },
        gradientFlow:    { '0%,100%': { backgroundPosition: '0% 50%' },                '50%': { backgroundPosition: '100% 50%' } },
        glowBorderPulse: { '0%,100%': { opacity: '0.45', transform: 'scaleY(0.65)' },  '50%': { opacity: '1', transform: 'scaleY(1)' } },
        slideInLeft:     { from: { opacity: '0', transform: 'translateX(-8px)' },                                       to:   { opacity: '1', transform: 'translateX(0)' } },
        countUp:         { from: { opacity: '0', transform: 'translateY(10px) scale(0.90)', filter: 'blur(3px)' },      to:   { opacity: '1', transform: 'translateY(0) scale(1)', filter: 'blur(0)' } },
        morphBlob:       { '0%,100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' }, '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' } },
      },

      transitionTimingFunction: {
        ease:   'cubic-bezier(.4,0,.2,1)',
        spring: 'cubic-bezier(.34,1.56,.64,1)',
      },
      transitionDuration: {
        fast:   '120ms',
        normal: '220ms',
        slow:   '360ms',
      },
    },
  },
  safelist: [
    'stagger', 'tilt-card', 'glass', 'aurora-bg', 'shimmer-bg', 'breathe',
    'nav-link-erp', 'nav-link-ops', 'nav-link-anal', 'nav-link-infra',
    'grp-erp-line', 'grp-ops-line', 'grp-anal-line', 'grp-infra-line',
    'grp-erp-text', 'grp-ops-text', 'grp-anal-text', 'grp-infra-text',
    'grp-dot-erp', 'grp-dot-ops', 'grp-dot-anal', 'grp-dot-infra',
    'float-hover', 'section-enter', 'pulse-glow', 'pulse-glow-red', 'pulse-glow-green',
    'nav-active', 'sidebar-premium', 'navbar-premium', 'logo-glow', 'mesh-bg',
    'gradient-sep', 'gradient-sep-subtle', 'card-premium', 'number-display', 'kpi-ghost-num',
    'card-shine', 'hover-lift',
    'text-gradient', 'text-gradient-gold', 'text-gradient-green', 'text-gradient-red',
    'glow-text', 'glow-text-green', 'glow-text-red', 'glow-text-yellow',
    'glow-text-purple', 'glow-text-cyan',
    'animate-slide-left', 'animate-count-up', 'animate-morph',
    { pattern: /^card-glow-/ },
    { pattern: /^animate-/ },
    { pattern: /^badge-/ },
    { pattern: /^icon-container-/ },
  ],
  plugins: [],
}
