import { lazy } from 'react'

export const ERPOrdensPage        = lazy(() => import('../features/erp/ordens/ERPOrdensPage'))
export const ERPEquipesPage       = lazy(() => import('../features/erp/equipes/EquipesPage'))
export const ERPDispatchPage      = lazy(() => import('../features/erp/dispatch/DispatchPage'))
export const ERPRelatoriosPage    = lazy(() => import('../features/erp/relatorios/RelatoriosPage'))
export const ERPAlertasPage       = lazy(() => import('../features/erp/alertas/AlertasPage'))
export const ERPRedePage          = lazy(() => import('../features/erp/rede/RedePage'))
export const ERPProdutividadePage = lazy(() => import('../features/erp/produtividade/ProdutividadePage'))
export const ERPQualidadePage     = lazy(() => import('../features/erp/qualidade/QualidadePage'))
export const ERPPlannerPage       = lazy(() => import('../features/erp/planner/PlannerPage'))

export const DashboardPage  = lazy(() => import('../features/dashboard/DashboardPage'))
export const OrdensPage     = lazy(() => import('../features/ordens/OrdensPage'))
export const CapacidadePage = lazy(() => import('../features/capacidade/CapacidadePage'))
export const GraficosPage   = lazy(() => import('../features/graficos/GraficosPage'))
export const CidadesPage    = lazy(() => import('../features/cidades/CidadesPage'))
export const CampoPage      = lazy(() => import('../features/campo/CampoPage'))
export const FornecedorPage = lazy(() => import('../features/fornecedor/FornecedorPage'))
export const JuniperPage    = lazy(() => import('../features/juniper/JuniperPage'))
export const NotFoundPage   = lazy(() => import('./NotFound'))
export const NocPage        = lazy(() => import('../features/noc/NocPage'))
export const FechamentoPage = lazy(() => import('../features/fechamento/FechamentoPage'))
export const MapaPage       = lazy(() => import('../features/mapa/MapaPage'))
export const GerencialPage  = lazy(() => import('../features/gerencial/GerencialPage'))
