export interface Team { code: string; leader: string; tipo: 'INSTALACAO' | 'MANUTENCAO' | 'REDE'; members: string[] }
export const TEAMS: Team[] = [
  { code: 'INST F01',  leader: 'FELIPE',    tipo: 'INSTALACAO', members: ['ANDERSON', 'MARCOS']    },
  { code: 'INST F04',  leader: 'THIAGO',    tipo: 'INSTALACAO', members: ['RAFAEL', 'GABRIEL']     },
  { code: 'INST F05',  leader: 'JADIEL',    tipo: 'INSTALACAO', members: ['WELLINGTON', 'PABLO']   },
  { code: 'INST F07',  leader: 'JHONATA',   tipo: 'INSTALACAO', members: ['ALEX', 'PAULO']         },
  { code: 'INST F08',  leader: 'ELCIO',     tipo: 'INSTALACAO', members: ['ROBERTO', 'FÁBIO']      },
  { code: 'INST F11',  leader: 'ADANS',     tipo: 'INSTALACAO', members: ['LEANDRO', 'SANDRO']     },
  { code: 'INST F12',  leader: 'CLAUDIO',   tipo: 'INSTALACAO', members: []                         },
  { code: 'INST F13',  leader: 'KAIQUE',    tipo: 'INSTALACAO', members: []                         },
  { code: 'INST F14',  leader: 'JOÃO',      tipo: 'INSTALACAO', members: []                         },
  { code: 'INST F20',  leader: 'LUCAS',     tipo: 'INSTALACAO', members: ['RENAN', 'HENRIQUE']     },
  { code: 'INST F27',  leader: 'CELSO',     tipo: 'INSTALACAO', members: ['DOUGLAS', 'EDSON']      },
  { code: 'INST F36',  leader: 'MAYKON',    tipo: 'INSTALACAO', members: ['VITOR', 'IGOR']         },
  { code: 'INST F39',  leader: 'RODRIGO',   tipo: 'INSTALACAO', members: ['ALAN', 'JEAN']          },
  { code: 'INST F44',  leader: 'WILLIAM',   tipo: 'INSTALACAO', members: ['CARLOS', 'DANILO']      },
  { code: 'INST F45',  leader: 'DIMAS',      tipo: 'INSTALACAO', members: ['FLÁVIO', 'RENATO']      },
  { code: 'INST F23',  leader: 'ANDERSON',  tipo: 'INSTALACAO', members: []                        },
  { code: 'INST F46',  leader: 'VANDERLEI', tipo: 'INSTALACAO', members: []                        },
  { code: 'INST F48',  leader: 'MATHEUS',   tipo: 'INSTALACAO', members: ['GUILHERME', 'TIAGO']    },
  { code: 'INST F49',  leader: 'BRUNO',     tipo: 'INSTALACAO', members: ['MARCELO', 'FABIANO']    },
  { code: 'INST F50',  leader: 'HIGOR',     tipo: 'INSTALACAO', members: ['JONATHAN', 'SAMUEL']    },
  { code: 'MANUT F02', leader: 'CLÁUDIO',   tipo: 'MANUTENCAO', members: ['ADRIANO', 'NILSON']     },
  { code: 'MANUT F04', leader: 'THAÍS',     tipo: 'MANUTENCAO', members: ['FERNANDA', 'SIMONE']    },
  { code: 'MANUT F77', leader: 'SERGIO',    tipo: 'MANUTENCAO', members: ['ALEXANDRE', 'GLAUBER']  },
  { code: 'REDE F01',  leader: 'LUCIANO',   tipo: 'REDE',       members: ['ÉDER', 'ROBSON']        },
  { code: 'REDE F04',  leader: 'SIDNEI',    tipo: 'REDE',       members: ['EMERSON', 'IVAN']       },
  { code: 'REDE F06',  leader: 'JULIO',     tipo: 'REDE',       members: ['MAURÍCIO', 'FÁBIO']     },
  { code: 'REDE F07',  leader: 'CARLOS',    tipo: 'REDE',       members: ['DIEGO', 'EVANDRO']      },
  { code: 'REDE F08',  leader: 'LEONARDO',  tipo: 'REDE',       members: ['CHRISTIAN', 'MAURO']    },
  { code: 'REDE F09',  leader: 'JEFFERSON', tipo: 'REDE',       members: ['ELVIS', 'LEANDRO']      },
  { code: 'REDE F10',  leader: 'VINÍCIUS',  tipo: 'REDE',       members: ['DALTON', 'OSMAR']       },
]
